package cloudinit

import (
	"bytes"
	"fmt"
	"text/template"
)

// NodeRole represents the type of node being provisioned
type NodeRole string

const (
	RoleEdge    NodeRole = "edge"
	RoleCompute NodeRole = "compute"
	RoleStorage NodeRole = "storage"
)

// TemplateData contains data for cloud-init template rendering
type TemplateData struct {
	NodeRole    NodeRole
	ForestID    string
	RegistryURL string // Optional: Morpheus registry for infrastructure state
	CallbackURL string // Optional: NimsForest callback URL for bootstrap trigger
	SSHKeys     []string

	// NimsForest auto-installation
	NimsForestInstall     bool   // Auto-install NimsForest
	NimsForestDownloadURL string // URL to download binary (e.g., "https://nimsforest.io/bin/nimsforest")

	// NATS server configuration
	NATSInstall  bool     // Auto-install NATS server
	NATSVersion  string   // NATS server version (e.g., "2.10.24")
	ClusterName  string   // NATS cluster name (typically the Forest ID)
	ClusterNodes []string // IPv6 addresses of existing nodes in the cluster
	IsFirstNode  bool     // True if this is the first node in the cluster
}

// EdgeNodeTemplate is the cloud-init script for edge nodes
// Morpheus responsibility: Infrastructure setup only (OS, network, firewall)
// NimsForest responsibility: NATS installation and configuration
const EdgeNodeTemplate = `#cloud-config

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - ufw
  - jq
  - systemd

write_files:
  - path: /etc/morpheus/node-info.json
    content: |
      {
        "forest_id": "{{.ForestID}}",
        "role": "{{.NodeRole}}",
        "provisioner": "morpheus",
        "provisioned_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
        "registry_url": "{{.RegistryURL}}",
        "callback_url": "{{.CallbackURL}}"
      }
    permissions: '0644'

  - path: /usr/local/bin/morpheus-bootstrap
    content: |
      #!/bin/bash
      # Morpheus bootstrap script - called by NimsForest
      set -e
      
      INSTANCE_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || echo "unknown")
      INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id || echo "unknown")
      LOCATION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone || echo "unknown")
      
      echo "Instance IP: $INSTANCE_IP"
      echo "Instance ID: $INSTANCE_ID"
      echo "Location: $LOCATION"
      
      # Export for nimsforest
      export MORPHEUS_IP=$INSTANCE_IP
      export MORPHEUS_INSTANCE_ID=$INSTANCE_ID
      export MORPHEUS_LOCATION=$LOCATION
    permissions: '0755'

runcmd:
  # Configure firewall - NATS ports for nimsforest
  - ufw allow 22/tcp comment 'SSH'
  - ufw allow 4222/tcp comment 'NATS client port'
  - ufw allow 6222/tcp comment 'NATS cluster port'
  - ufw allow 8222/tcp comment 'NATS monitoring port'
  - ufw allow 7777/tcp comment 'NATS leafnode port'
  - ufw --force enable
  
  # Create directories for nimsforest (binaries, data, logs)
  - mkdir -p /opt/nimsforest/bin /var/lib/nimsforest /var/log/nimsforest /etc/nimsforest
  - chown -R ubuntu:ubuntu /opt/nimsforest /var/lib/nimsforest /var/log/nimsforest /etc/nimsforest
  
  # Prepare for direct binary deployment (systemd services managed by NimsForest)
  - systemctl daemon-reload
  
  # Get instance metadata
  - /usr/local/bin/morpheus-bootstrap
  
  {{if .NATSInstall}}
  # Download and install NATS server
  - |
    echo "📦 Installing NATS server {{.NATSVersion}}..."
    NATS_VERSION="{{.NATSVersion}}"
    ARCH=$(uname -m)
    if [ "$ARCH" = "x86_64" ]; then
      ARCH="amd64"
    elif [ "$ARCH" = "aarch64" ]; then
      ARCH="arm64"
    fi
    
    NATS_URL="https://github.com/nats-io/nats-server/releases/download/v${NATS_VERSION}/nats-server-v${NATS_VERSION}-linux-${ARCH}.tar.gz"
    echo "📥 Downloading from ${NATS_URL}..."
    
    if curl -fsSL "$NATS_URL" | tar xz -C /tmp; then
      mv /tmp/nats-server-v${NATS_VERSION}-linux-${ARCH}/nats-server /usr/local/bin/
      chmod +x /usr/local/bin/nats-server
      echo "✅ NATS server installed"
    else
      echo "❌ Failed to download NATS server"
      exit 1
    fi
  
  # Create NATS directories
  - mkdir -p /etc/nats /var/lib/nats/jetstream
  - chown -R ubuntu:ubuntu /var/lib/nats
  
  # Generate NATS configuration
  - |
    cat > /etc/nats/nats.conf << 'NATSEOF'
    # NATS Server Configuration
    # Generated by Morpheus
    
    port: 4222
    http_port: 8222
    
    # JetStream configuration
    jetstream {
      store_dir: /var/lib/nats/jetstream
      max_mem: 1G
      max_file: 10G
    }
    
    # Cluster configuration
    cluster {
      name: {{.ClusterName}}
      port: 6222
      {{if not .IsFirstNode}}
      routes = [
        {{range .ClusterNodes}}
        nats-route://[{{.}}]:6222
        {{end}}
      ]
      {{end}}
    }
    
    # Logging
    debug: false
    trace: false
    logtime: true
    NATSEOF
    echo "✅ NATS configuration created"
  
  # Create NATS systemd service
  - |
    cat > /etc/systemd/system/nats.service << 'NATSSERVICEEOF'
    [Unit]
    Description=NATS Server
    After=network.target

    [Service]
    Type=simple
    ExecStart=/usr/local/bin/nats-server -c /etc/nats/nats.conf
    Restart=always
    RestartSec=5
    User=ubuntu
    Group=ubuntu
    LimitNOFILE=65536

    [Install]
    WantedBy=multi-user.target
    NATSSERVICEEOF
    
    # Remove leading spaces from the service file
    sed -i 's/^    //' /etc/systemd/system/nats.service
    
    systemctl daemon-reload
    systemctl enable nats
    systemctl start nats
    echo "✅ NATS server started"
  {{end}}
  
  {{if .NimsForestInstall}}
  # Download and install NimsForest
  - |
    echo "📦 Installing NimsForest..."
    DOWNLOAD_URL="{{.NimsForestDownloadURL}}"
    
    echo "📥 Downloading from ${DOWNLOAD_URL}..."
    if curl -fsSL -o /opt/nimsforest/bin/nimsforest "$DOWNLOAD_URL"; then
      chmod +x /opt/nimsforest/bin/nimsforest
      echo "✅ NimsForest installed"
      
      cat > /etc/systemd/system/nimsforest.service << 'SERVICEEOF'
      [Unit]
      Description=NimsForest Service
      After=network.target{{if .NATSInstall}} nats.service{{end}}
      Wants=network-online.target
      {{if .NATSInstall}}Requires=nats.service{{end}}

      [Service]
      Type=simple
      User=ubuntu
      Group=ubuntu
      ExecStart=/opt/nimsforest/bin/nimsforest start --forest-id {{.ForestID}}
      Restart=always
      RestartSec=5
      Environment=FOREST_ID={{.ForestID}}
      Environment=NODE_ROLE={{.NodeRole}}
      {{if .NATSInstall}}Environment=NATS_URL=nats://localhost:4222{{end}}
      WorkingDirectory=/var/lib/nimsforest

      [Install]
      WantedBy=multi-user.target
      SERVICEEOF
      
      sed -i 's/^      //' /etc/systemd/system/nimsforest.service
      systemctl daemon-reload
      systemctl enable nimsforest
      systemctl start nimsforest
      echo "✅ NimsForest service started"
    else
      echo "⚠️  Failed to download NimsForest from ${DOWNLOAD_URL}"
    fi
  {{end}}
  
  # Signal readiness to registry
  - |
    INSTANCE_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || echo "unknown")
    INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id || hostname)
    LOCATION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone || echo "unknown")
    
    if [ "{{.RegistryURL}}" != "" ]; then
      curl -X POST {{.RegistryURL}}/api/v1/nodes \
        -H "Content-Type: application/json" \
        -d "{
          \"forest_id\": \"{{.ForestID}}\",
          \"node_id\": \"$INSTANCE_ID\",
          \"role\": \"{{.NodeRole}}\",
          \"ip\": \"$INSTANCE_IP\",
          \"location\": \"$LOCATION\",
          \"status\": \"infrastructure_ready\",
          \"provisioner\": \"morpheus\"
        }" || echo "Registry notification failed (expected if registry not available)"
    fi
  
  # Trigger nimsforest bootstrap if callback URL provided
  - |
    if [ "{{.CallbackURL}}" != "" ]; then
      INSTANCE_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || echo "unknown")
      INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id || hostname)
      
      curl -X POST {{.CallbackURL}}/api/v1/bootstrap \
        -H "Content-Type: application/json" \
        -d "{
          \"forest_id\": \"{{.ForestID}}\",
          \"node_id\": \"$INSTANCE_ID\",
          \"node_ip\": \"$INSTANCE_IP\",
          \"role\": \"{{.NodeRole}}\"
        }" || echo "NimsForest callback failed (will retry via polling)"
    fi

final_message: "Morpheus infrastructure provisioning complete. Ready for NimsForest bootstrap."
`

// ComputeNodeTemplate is the cloud-init script for compute nodes
// Morpheus responsibility: Infrastructure setup only
// NimsForest responsibility: Worker/compute service installation
const ComputeNodeTemplate = `#cloud-config

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - ufw
  - jq
  - systemd

write_files:
  - path: /etc/morpheus/node-info.json
    content: |
      {
        "forest_id": "{{.ForestID}}",
        "role": "{{.NodeRole}}",
        "provisioner": "morpheus",
        "provisioned_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
        "registry_url": "{{.RegistryURL}}",
        "callback_url": "{{.CallbackURL}}"
      }
    permissions: '0644'

runcmd:
  # Configure firewall - minimal for compute
  - ufw allow 22/tcp comment 'SSH'
  - ufw allow 4222/tcp comment 'NATS client connection'
  - ufw --force enable
  
  # Create directories for nimsforest (binaries, data, logs)
  - mkdir -p /opt/nimsforest/bin /var/lib/nimsforest /var/log/nimsforest /etc/nimsforest
  - chown -R ubuntu:ubuntu /opt/nimsforest /var/lib/nimsforest /var/log/nimsforest /etc/nimsforest
  
  # Prepare for direct binary deployment
  - systemctl daemon-reload
  
  {{if .NimsForestInstall}}
  # Download and install NimsForest
  - |
    echo "📦 Installing NimsForest..."
    DOWNLOAD_URL="{{.NimsForestDownloadURL}}"
    
    echo "📥 Downloading from ${DOWNLOAD_URL}..."
    if curl -fsSL -o /opt/nimsforest/bin/nimsforest "$DOWNLOAD_URL"; then
      chmod +x /opt/nimsforest/bin/nimsforest
      echo "✅ NimsForest installed"
      
      cat > /etc/systemd/system/nimsforest.service << 'SERVICEEOF'
      [Unit]
      Description=NimsForest Service
      After=network.target
      Wants=network-online.target

      [Service]
      Type=simple
      User=ubuntu
      Group=ubuntu
      ExecStart=/opt/nimsforest/bin/nimsforest start --forest-id {{.ForestID}}
      Restart=always
      RestartSec=5
      Environment=FOREST_ID={{.ForestID}}
      Environment=NODE_ROLE={{.NodeRole}}
      WorkingDirectory=/var/lib/nimsforest

      [Install]
      WantedBy=multi-user.target
      SERVICEEOF

      sed -i 's/^      //' /etc/systemd/system/nimsforest.service
      systemctl daemon-reload
      systemctl enable nimsforest
      systemctl start nimsforest
      echo "✅ NimsForest service started"
    else
      echo "⚠️  Failed to download NimsForest from ${DOWNLOAD_URL}"
    fi
  {{end}}
  
  # Signal readiness
  - |
    INSTANCE_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || echo "unknown")
    INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id || hostname)
    LOCATION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone || echo "unknown")
    
    if [ "{{.RegistryURL}}" != "" ]; then
      curl -X POST {{.RegistryURL}}/api/v1/nodes \
        -H "Content-Type: application/json" \
        -d "{
          \"forest_id\": \"{{.ForestID}}\",
          \"node_id\": \"$INSTANCE_ID\",
          \"role\": \"{{.NodeRole}}\",
          \"ip\": \"$INSTANCE_IP\",
          \"location\": \"$LOCATION\",
          \"status\": \"{{if .NimsForestInstall}}active{{else}}infrastructure_ready{{end}}\",
          \"provisioner\": \"morpheus\"
        }" || echo "Registry notification failed"
    fi
  
  # Trigger nimsforest bootstrap (only if not auto-installed)
  {{if not .NimsForestInstall}}
  - |
    if [ "{{.CallbackURL}}" != "" ]; then
      INSTANCE_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || echo "unknown")
      INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id || hostname)
      
      curl -X POST {{.CallbackURL}}/api/v1/bootstrap \
        -H "Content-Type: application/json" \
        -d "{
          \"forest_id\": \"{{.ForestID}}\",
          \"node_id\": \"$INSTANCE_ID\",
          \"node_ip\": \"$INSTANCE_IP\",
          \"role\": \"{{.NodeRole}}\"
        }" || echo "NimsForest callback failed"
    fi
  {{end}}

final_message: "Morpheus provisioning complete.{{if .NimsForestInstall}} NimsForest installed and running.{{else}} Ready for NimsForest bootstrap.{{end}}"
`

// StorageNodeTemplate is the cloud-init script for storage nodes
// Morpheus responsibility: Infrastructure setup (NFS, firewall)
// NimsForest responsibility: Storage orchestration and management
const StorageNodeTemplate = `#cloud-config

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - nfs-kernel-server
  - ufw
  - jq

write_files:
  - path: /etc/morpheus/node-info.json
    content: |
      {
        "forest_id": "{{.ForestID}}",
        "role": "{{.NodeRole}}",
        "provisioner": "morpheus",
        "provisioned_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
        "registry_url": "{{.RegistryURL}}",
        "callback_url": "{{.CallbackURL}}"
      }
    permissions: '0644'

  - path: /etc/exports
    content: |
      # NFS exports - managed by NimsForest
      /mnt/nimsforest-storage *(rw,sync,no_subtree_check,no_root_squash)

runcmd:
  # Setup base storage directory
  - mkdir -p /mnt/nimsforest-storage
  - chmod 755 /mnt/nimsforest-storage
  - chown ubuntu:ubuntu /mnt/nimsforest-storage
  
  # Configure NFS
  - systemctl enable nfs-kernel-server
  - systemctl start nfs-kernel-server
  - exportfs -ra
  
  # Configure firewall
  - ufw allow 22/tcp comment 'SSH'
  - ufw allow 2049/tcp comment 'NFS'
  - ufw allow 111/tcp comment 'RPC'
  - ufw allow 111/udp comment 'RPC'
  - ufw allow 4222/tcp comment 'NATS client'
  - ufw --force enable
  
  {{if .NimsForestInstall}}
  # Download and install NimsForest
  - |
    echo "📦 Installing NimsForest..."
    DOWNLOAD_URL="{{.NimsForestDownloadURL}}"
    
    echo "📥 Downloading from ${DOWNLOAD_URL}..."
    if curl -fsSL -o /opt/nimsforest/bin/nimsforest "$DOWNLOAD_URL"; then
      chmod +x /opt/nimsforest/bin/nimsforest
      echo "✅ NimsForest installed"
      
      cat > /etc/systemd/system/nimsforest.service << 'SERVICEEOF'
      [Unit]
      Description=NimsForest Service
      After=network.target
      Wants=network-online.target

      [Service]
      Type=simple
      User=ubuntu
      Group=ubuntu
      ExecStart=/opt/nimsforest/bin/nimsforest start --forest-id {{.ForestID}}
      Restart=always
      RestartSec=5
      Environment=FOREST_ID={{.ForestID}}
      Environment=NODE_ROLE={{.NodeRole}}
      WorkingDirectory=/var/lib/nimsforest

      [Install]
      WantedBy=multi-user.target
      SERVICEEOF

      sed -i 's/^      //' /etc/systemd/system/nimsforest.service
      systemctl daemon-reload
      systemctl enable nimsforest
      systemctl start nimsforest
      echo "✅ NimsForest service started"
    else
      echo "⚠️  Failed to download NimsForest from ${DOWNLOAD_URL}"
    fi
  {{end}}
  
  # Signal readiness
  - |
    INSTANCE_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || echo "unknown")
    INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id || hostname)
    LOCATION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone || echo "unknown")
    
    if [ "{{.RegistryURL}}" != "" ]; then
      curl -X POST {{.RegistryURL}}/api/v1/nodes \
        -H "Content-Type: application/json" \
        -d "{
          \"forest_id\": \"{{.ForestID}}\",
          \"node_id\": \"$INSTANCE_ID\",
          \"role\": \"{{.NodeRole}}\",
          \"ip\": \"$INSTANCE_IP\",
          \"location\": \"$LOCATION\",
          \"status\": \"{{if .NimsForestInstall}}active{{else}}infrastructure_ready{{end}}\",
          \"provisioner\": \"morpheus\",
          \"storage_path\": \"/mnt/nimsforest-storage\"
        }" || echo "Registry notification failed"
    fi
  
  {{if not .NimsForestInstall}}
  # Trigger nimsforest bootstrap
  - |
    if [ "{{.CallbackURL}}" != "" ]; then
      INSTANCE_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || echo "unknown")
      INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id || hostname)
      
      curl -X POST {{.CallbackURL}}/api/v1/bootstrap \
        -H "Content-Type: application/json" \
        -d "{
          \"forest_id\": \"{{.ForestID}}\",
          \"node_id\": \"$INSTANCE_ID\",
          \"node_ip\": \"$INSTANCE_IP\",
          \"role\": \"{{.NodeRole}}\"
        }" || echo "NimsForest callback failed"
    fi
  {{end}}

final_message: "Morpheus provisioning complete.{{if .NimsForestInstall}} NimsForest installed and running.{{else}} Ready for NimsForest bootstrap.{{end}}"
`

// Generate creates a cloud-init script for the given role and data
func Generate(role NodeRole, data TemplateData) (string, error) {
	var tmplStr string

	switch role {
	case RoleEdge:
		tmplStr = EdgeNodeTemplate
	case RoleCompute:
		tmplStr = ComputeNodeTemplate
	case RoleStorage:
		tmplStr = StorageNodeTemplate
	default:
		return "", fmt.Errorf("unknown node role: %s", role)
	}

	// Add template functions
	funcMap := template.FuncMap{
		"sub": func(a, b int) int { return a - b },
	}

	tmpl, err := template.New("cloudinit").Funcs(funcMap).Parse(tmplStr)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}
